// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ylminxgdupwynqwwwtqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlsbWlueGdkdXB3eW5xd3d3dHFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYwMjU3MzEsImV4cCI6MjA5MTYwMTczMX0.u5qcne-BCfK61qTF7kTflWPzLEUt49xVKyH0DCoCwKU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});